### ISSUE TITLE
Unable to View Removed LR Images

### ISSUE THREAD

**Issue by feijoes** [dokkanlr/dokkanlr.github.io#1]
I was checking your website, and I couldn't see the images from the removed LR list there.
![image](https://github.com/dokkanlr/dokkanlr.github.io/assets/74252371/8ebf4259-2852-487d-839f-85df2600ac64)

I checked the console and your code, and I noticed that in the special list (where the excluded LR cards are), it was searching for the images with a .png extension in line 124 of the script.js file:
```js
    flair.setAttribute('src', 'images/icons/'+disabled[i].id+'.png'); 
```
I changed the extension from `.png` to `.webp`, and it worked perfectly:

![image](https://github.com/dokkanlr/dokkanlr.github.io/assets/74252371/ef77777e-b676-4778-ac0c-a4649c3a772b)

Normally, when I encounter a problem, I create a fork and commit a fix, but in this case, it's just one line of code. Hence, I'm creating this issue.

**Comment by antonlabz** [comment]
Hi @feijoes, thank you for bringing this to my attention. It was a slight oversight on my part as I had forgotten to update this line when I switched the rest of the images over to WEBP format.

The updated code has been pushed and should be live shortly.
